NumPy (Numerical Python) is a fundamental library for scientific computing in Python. It provides a powerful data structure called `ndarray` (N-dimensional array) that allows efficient manipulation of large arrays and matrices of numeric data.

### Importing NumPy

To use NumPy, you need to import the library. Conventionally, it is imported under the alias `np`:


In [2]:
import numpy as np

### Creating NumPy Arrays

NumPy arrays are created using the `np.array()` function. You can pass a Python list, tuple, or any iterable object to create an array:


In [3]:

import numpy as np

# Create a 1D array
arr1 = np.array([1, 2, 3, 4, 5])
print(arr1)
# Output: [1 2 3 4 5]

# Create a 2D array
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print(arr2)
# Output: [[1 2 3]
#          [4 5 6]]


[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]


### Array Attributes

NumPy arrays have various attributes that provide information about the array:


In [4]:

import numpy as np

arr = np.array([1, 2, 3, 4, 5])

# Shape of the array
print(arr.shape)
# Output: (5,)

# Number of dimensions
print(arr.ndim)
# Output: 1

# Data type of the array
print(arr.dtype)
# Output: int64


(5,)
1
int32



### Array Operations

NumPy arrays support element-wise operations, which allows you to perform mathematical operations on entire arrays without the need for loops:


In [5]:

import numpy as np

arr = np.array([1, 2, 3, 4, 5])

# Addition
result = arr + 5
print(result)
# Output: [ 6  7  8  9 10]

# Multiplication
result = arr * 2
print(result)
# Output: [ 2  4  6  8 10]

# Element-wise square root
result = np.sqrt(arr)
print(result)
# Output: [1.         1.41421356 1.73205081 2.         2.23606798]


[ 6  7  8  9 10]
[ 2  4  6  8 10]
[1.         1.41421356 1.73205081 2.         2.23606798]


### Array Indexing and Slicing

NumPy arrays can be indexed and sliced similar to Python lists:


In [6]:



import numpy as np

arr = np.array([1, 2, 3, 4, 5])

# Accessing individual elements
print(arr[0])
# Output: 1

# Slicing the array
print(arr[2:4])
# Output: [3 4]

# Assigning new values to a slice
arr[1:3] = [10, 20]
print(arr)
# Output: [ 1 10 20  4  5]



1
[3 4]
[ 1 10 20  4  5]




### Array Shape Manipulation

NumPy provides several functions to manipulate the shape of arrays:


In [7]:

import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

# Transpose of the array
print(arr.T)
# Output: [[1 4]
#          [2 5]
#          [3 6]]

# Reshaping the array
new_shape = (3, 2)
print(arr.reshape(new_shape))
# Output: [[1 2]
#          [3 4]
#          [5 6]]


[[1 4]
 [2 5]
 [3 6]]
[[1 2]
 [3 4]
 [5 6]]


These are just some of the basic features and functionalities of NumPy. There are many more advanced features and functions available in NumPy, such as mathematical operations, statistical functions, linear algebra operations, and more.

Here are a few additional examples:

### Mathematical Operations

NumPy provides a wide range of mathematical functions that operate element-wise on arrays:


In [8]:

import numpy as np

arr = np.array([1, 2, 3, 4, 5])

# Sum of all elements
print(np.sum(arr))
# Output: 15

# Maximum and minimum values
print(np.max(arr))
# Output: 5
print(np.min(arr))
# Output: 1

# Element-wise exponential function
result = np.exp(arr)
print(result)
# Output: [  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]


15
5
1
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]



### Statistical Functions

NumPy offers a variety of statistical functions to analyze data:


In [9]:

import numpy as np

arr = np.array([1, 2, 3, 4, 5])

# Mean of the array
print(np.mean(arr))
# Output: 3.0

# Standard deviation
print(np.std(arr))
# Output: 1.4142135623730951

# Correlation coefficient
arr2 = np.array([2, 4, 6, 8, 10])
print(np.corrcoef(arr, arr2))
# Output: [[1. 1.]
#          [1. 1.]]


3.0
1.4142135623730951
[[1. 1.]
 [1. 1.]]


### Linear Algebra Operations

NumPy provides extensive support for linear algebra operations:


In [10]:
import numpy as np

arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])

# Matrix multiplication
result = np.matmul(arr1, arr2)
print(result)
# Output: [[19 22]
#          [43 50]]

# Matrix determinant
print(np.linalg.det(arr1))
# Output: -2.0

# Eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(arr1)
print(eigenvalues)
# Output: [-0.37228132  5.37228132]
print(eigenvectors)
# Output: [[-0.82456484 -0.41597356]
#          [ 0.56576746 -0.90937671]]

[[19 22]
 [43 50]]
-2.0000000000000004
[-0.37228132  5.37228132]
[[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


These examples provide just a glimpse of what can be achieved with NumPy. The library offers a wide range of functions, tools, and capabilities for efficient numerical computing and data manipulation in Python.